package com.cmg.pl.dailytest;

import com.thoughtworks.selenium.Selenium;
import com.thoughtworks.selenium.webdriven.WebDriverBackedSelenium;

import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebDriver;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;
import static com.c_mg.pl.selenium.PLAUTOTEST.TakeScreenShot.*;

public class PLDailyTestCase11Test {
	private Selenium selenium;

	@Before
	public void setUp() throws Exception {
		WebDriver driver = new FirefoxDriver();
		String baseUrl = "https://pensionline.bp.com/content/pl/";
		selenium = new WebDriverBackedSelenium(driver, baseUrl);
		init(driver);
	}

	@Test
	public void testPLDailyTestCase11() throws Exception {
		// Begin to check report "Checking connection to all data source" !
		System.out.println("Begin to check report generated by auto_daily_checker");
		selenium.open("/content/pl");
		selenium.click("link=Login");
		selenium.waitForPageToLoad("30000");
		selenium.type("id=_request_username", "auto_daily_checker");
		selenium.type("id=_request_password", "P3nsions");
		selenium.click("id=doauth");
		selenium.waitForPageToLoad("3000");
		Thread.sleep(8000);
		selenium.click("link=Reporting Tool");
		selenium.waitForPageToLoad("3000");
		Thread.sleep(8000);
		assertTrue(selenium.isElementPresent("//div[@id='content']/div[@class='ws_report_list']/div[@class='ws_report']/div[2][@class='ws_report_text']/h2//a[contains(text(),'Checking connection to all data source')]"));
		selenium.click("link=Checking connection to all data sources");
		selenium.waitForPageToLoad("30000");
		selenium.click("id=_add_report");
		Thread.sleep(8000);
		selenium.click("id=_run_report_confirm");
		// Check if the report is generated successfully...
		Thread.sleep(60000);
		selenium.selectWindow("Report generation completed");
		assertTrue(selenium.isElementPresent("//div[@id='content']/h1[contains(text(),'Report generation completed')]"));
		// May take a snapshot here
		takeScreenshoot();
		Thread.sleep(8000);
		selenium.click("link=Logout");
		selenium.waitForPageToLoad("30000");
		Thread.sleep(8000);
		assertTrue(selenium.isElementPresent("//input[@class='goButton']"));
		Thread.sleep(8000);
		selenium.click("//input[@class='goButton']");
		// Finish
		System.out.println("Generate report \"Checking connection to all data source\" successfully!");
	}

	@After
	public void tearDown() throws Exception {
		selenium.stop();
	}
}
